### ISSUE TITLE
Switching filename to .simpspector.yml (like travis, scruitinizer and other)

### ISSUE THREAD

**Issue by dragonito** [simplethings/SimpSpector#108]
from tolry:

"Not specific to this PR, but: what about switching the filename to ".simpspector.yml" as travis, scrutinizer and others do? Keeps the "normal" file listing clean and denotes that this file might not directly important for users. Any thoughts?"

**Comment by tolry** [comment]
:+1:

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
already done in simplethings/simpspector#107
