### ISSUE TITLE
integrate phpmetrics

### ISSUE THREAD

**Issue by tolry** [simplethings/SimpSpector#87]
This will probably not be a simple gadget as I am not really sure how to integrate this with our current architecture, but looks "really cool" :smile: 

sitepoint article http://www.sitepoint.com/visualize-codes-quality-phpmetrics/
homepage http://www.phpmetrics.org/
example http://www.phpmetrics.org/report/latest/index.html

thanks to th for the hint

**Comment by dragonito** [comment]
+1

**Comment by larsborn** [comment]
did we speak about this last time? Or should we do this tomorrow?

**Comment by DavidBadura** [comment]
tomorrow :wink:

**Comment by tolry** [comment]
Doesn't have to do anything with the metrics we discussed today, does it? Shall we move this to the far future?

**Comment by tolry** [comment]
This issue was moved to simplethings/simpspector-analyser#15
